#colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
pink=$(tput bold ; tput setaf 5)
reset=$(tput sgr0)

gitStatus() { git diff --quiet 2> /dev/null || echo ' *' ; }
gitBranch() { git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/ (\1$(gitStatus))/" ; }

PS1="[\[$green\]\T\[$reset\]] \[$red\]\u\[$reset\] [\[$cyan\]\w\[$reset\]]\[$pink\]\$(gitBranch)\[$reset\] \$ "
PS2=" > "

# the path is initially set to "/bin:/sbin:/usr/bin:/usr/sbin"
export PATH=/usr/local/bin:$PATH:./bin

# aliases
alias l="ls -l"
alias ll="ls -al"
alias g="git"
alias reload="source ~/.bash_profile"
alias redis="redis-server /usr/local/etc/redis.conf"
alias worker="QUEUE=* bundle exec rake resque:work"
alias unic="CACHE=true bundle exec unicorn_rails -c config/unicorn_development.rb"
alias uni="bundle exec unicorn_rails -c config/unicorn_development.rb"
alias rdb="rake db:migrate db:test:prepare"
alias be="bundle exec"

source ~/.git-completion.sh

# Shut off control flow in terminal so we can use vim shortcut <c-s>
stty -ixon -ixoff

export RUBY_GC_MALLOC_LIMIT=60000000
export RUBY_FREE_MIN=200000

# set up your git credentials, rbenv or rvm init, any special PATH or configs, etc
source .extra
