# set PATH in ~/.extra after ruby paths are added
# the path is initially set to "/bin:/sbin:/usr/bin:/usr/sbin"
# export PATH="./script:./bin:~/bin:/usr/local/bin:$PATH"

# set the default editor in a way that works with `git commit`
export EDITOR="vim -f"

# aliases
alias ls="ls -p"
alias l="ls -l"
alias ll="ls -al"
alias g="git"
alias gg="gitsh"
alias v="vim"
alias reload="source ~/.bash_profile"
alias redis="redis-server /usr/local/etc/redis.conf"
alias worker="QUEUE=* bundle exec rake resque:work"
alias unic="CACHE=true bundle exec unicorn_rails -c config/unicorn_development.rb"
alias uni="bundle exec unicorn_rails -c config/unicorn_development.rb"
alias rdb="rake db:migrate RAILS_ENV=test"
alias be="bundle exec"
alias b="bundle"
alias spec="time spec -cf n"
alias db="rake db:migrate RAILS_ENV=test"
alias u="rails s"
alias f="foreman start"
alias j="jekyll serve --baseurl ''"
alias m="be middleman"
alias vag="vagrant up && vagrant ssh"
alias halt="vagrant halt"
alias wow="git s"
alias such=git
alias very=git
alias y="git s" # overzealous patchwise commits!

# Alias hub as git; hub is a fantastic package
eval "$(hub alias -s)"

# Shut off control flow in terminal so we can use vim shortcut <c-s>
stty -ixon -ixoff

export LANGUAGE="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

source ~/.functions

############################
# PROMPT
############################
#colors
red=$(tput setaf 1)
green=$(tput setaf 2)
cyan=$(tput setaf 6)
pink=$(tput setaf 5)
reset=$(tput sgr0)

if hash brew 2>/dev/null && [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS1_SHOWUNTRACKEDFILES=1
elif [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
  export GIT_PS1_SHOWDIRTYSTATE=1
  export GIT_PS1_SHOWSTASHSTATE=1
  export GIT_PS1_SHOWUNTRACKEDFILES=1
else
  function parse_git_dirty() {
    [[ $(command git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo " *"
  }
  function __git_ps1() {
    command git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty) /"
  }
fi
function nick() {
  cat ~/.machine_nickname
}
if [[ `nick` = "local" ]]; then
  nickcolor=$green
else
  nickcolor=$red
fi
PS1="\[$cyan\]\W\[$reset\] \[$pink\]\$(__git_ps1 %s' ')\[$reset\]\$ "
PS2=" > "

# set up your git credentials, rbenv or rvm init, any special PATH or configs, etc
source ~/.extra
